/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Markdown2HTMLPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var Markdown2HTMLPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.addRibbonIcon("file-text", "\u590D\u5236\u5230 Markdown2HTML", async () => {
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (activeView) {
        const editor = activeView.editor;
        const content = editor.getValue();
        try {
          const processedContent = await this.processImages(content, activeView.file);
          await navigator.clipboard.writeText(processedContent);
          new import_obsidian.Notice("\u5185\u5BB9\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F");
        } catch (error) {
          const clipboardError = error;
          console.error("Error:", clipboardError);
          new import_obsidian.Notice(`\u590D\u5236\u5931\u8D25\uFF1A${clipboardError.message}`);
        }
      } else {
        new import_obsidian.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u6587\u4EF6");
      }
    });
    this.addCommand({
      id: "copy-to-markdown2html",
      name: "\u590D\u5236\u5F53\u524D\u6587\u6863\u5230\u526A\u8D34\u677F",
      editorCallback: async (editor, view) => {
        const content = editor.getValue();
        try {
          const processedContent = await this.processImages(content, view.file);
          await navigator.clipboard.writeText(processedContent);
          new import_obsidian.Notice("\u5185\u5BB9\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F");
        } catch (error) {
          const clipboardError = error;
          console.error("Error:", clipboardError);
          new import_obsidian.Notice(`\u590D\u5236\u5931\u8D25\uFF1A${clipboardError.message}`);
        }
      }
    });
  }
  // 处理所有图片
  async processImages(content, currentFile) {
    if (!currentFile) {
      return content;
    }
    const imageRegex = /!\[(.*?)\]\((.*?)\)/g;
    const vault = this.app.vault;
    let processedContent = "";
    let lastIndex = 0;
    let match = imageRegex.exec(content);
    let hasLocalImages = false;
    while (match !== null) {
      const [fullMatch, altText, imagePath] = match;
      processedContent += content.slice(lastIndex, match.index);
      if (!imagePath.startsWith("http://") && !imagePath.startsWith("https://")) {
        try {
          const resolvedPath = this.resolveImagePath(imagePath, currentFile);
          const imageFile = vault.getAbstractFileByPath(resolvedPath);
          if (imageFile instanceof import_obsidian.TFile) {
            hasLocalImages = true;
            const arrayBuffer = await vault.readBinary(imageFile);
            const base64String = this.arrayBufferToBase64(arrayBuffer);
            const mimeType = this.getMimeType(imageFile.extension);
            const dataUrl = `data:${mimeType};base64,${base64String}`;
            processedContent += `![${altText}](obsidian-base64://${dataUrl})`;
          } else {
            processedContent += fullMatch;
          }
        } catch (error) {
          console.error("Error processing image path:", error);
          processedContent += fullMatch;
        }
      } else {
        processedContent += fullMatch;
      }
      lastIndex = match.index + fullMatch.length;
      match = imageRegex.exec(content);
    }
    processedContent += content.slice(lastIndex);
    if (hasLocalImages) {
      return `<!--obsidian-markdown2html-start-->
${processedContent}
<!--obsidian-markdown2html-end-->`;
    }
    return processedContent;
  }
  // 解析图片路径（相对于当前文件）
  resolveImagePath(originalPath, currentFile) {
    var _a;
    if (originalPath.startsWith("/")) {
      return originalPath.slice(1);
    }
    const currentDir = ((_a = currentFile.parent) == null ? void 0 : _a.path) || "";
    let processedPath = originalPath;
    if (processedPath.startsWith("./")) {
      processedPath = processedPath.slice(2);
    }
    return currentDir ? `${currentDir}/${processedPath}` : processedPath;
  }
  // 将 ArrayBuffer 转换为 base64 字符串
  arrayBufferToBase64(buffer) {
    let binary = "";
    const bytes = new Uint8Array(buffer);
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return window.btoa(binary);
  }
  // 根据文件扩展名获取 MIME 类型
  getMimeType(extension) {
    const mimeTypes = {
      "png": "image/png",
      "jpg": "image/jpeg",
      "jpeg": "image/jpeg",
      "gif": "image/gif",
      "webp": "image/webp",
      "svg": "image/svg+xml"
    };
    return mimeTypes[extension.toLowerCase()] || "image/png";
  }
};
